### ISSUE TITLE
chore: Update Readme Demo Steps

### ISSUE THREAD

**Issue by TristanHoladay** [defenseunicorns-labs/lula1#130]
## Description

The current readme has a list of steps for getting started with Lula. Some of these steps and their output no longer match what is actually occurring when they are applied.

```
tristan@tristan-NUC13ANHi7:~/repos/lula$ kubectl apply -f ./demo/namespace.yaml
namespace/validation-test created

tristan@tristan-NUC13ANHi7:~/repos/lula$ kubectl apply -f ./demo/pod.fail.yaml
pod/demo-pod-fail created

tristan@tristan-NUC13ANHi7:~/repos/lula$ ./lula validate ./demo/oscal-component.yaml
bash: ./lula: No such file or directory

tristan@tristan-NUC13ANHi7:~/repos/lula$ ./bin/lula validate ./demo/oscal-component.yaml
OPA provider validating...
UUID: 42C2FFDC-5F05-44DF-A67F-EEC8660AEFFD
	Status: not-satisfied
	
tristan@tristan-NUC13ANHi7:~/repos/lula$ kubectl apply -f ./demo/pod.pass.yaml
pod/demo-pod created

tristan@tristan-NUC13ANHi7:~/repos/lula$ ./bin/lula validate ./demo/oscal-component.yaml
OPA provider validating...
UUID: 42C2FFDC-5F05-44DF-A67F-EEC8660AEFFD
	Status: not-satisfied
```
## ToDos
- [x] update steps with  `./lula` to `./bin/lula`
- [x] show new output for pod failing
      OPA provider validating...
      UUID: 42C2FFDC-5F05-44DF-A67F-EEC8660AEFFD
	Status: not-satisfied
  
- [ ] add step to delete the failed pod before running validate for the passing pod
   `kubectl delete -f demo/pod.fail.yaml`

**Comment by brandtkeller** [comment]
Updated in #142 

Changed the behavior of the demo such that the pod is updated in-place and thus a `kubectl delete` is not required.
