### ISSUE TITLE
Homebrew Release Process

### ISSUE THREAD

**Issue by CloudBeard** [defenseunicorns-labs/lula1#182]
# Homebrew Release Process
We are utilizing Goreleaser to cut releases for Lula. Goreleaser uses a .goreleaser.yaml config file that sets up the release for GitHub and for Homebrew.

## Issue
Currently we are unable to split the Goreleaser config in a way that will allow us to use multiple steps in CI to one create the release binaries and release for GitHub and second step to push the binaries into our homebrew-tap repo.

We are using GitHub App to provide access to the homebrew-tap repo by creating a token to pass to Goreleaser to access that repo. To push the releaser binaries and release to GitHub we are using a separate token that has access to the repo. GitHub Apps currently do not provide a way to split the permissions up to allow us to use the GitHub App to do both.

## Possible Solution
A possible solution could be to use Pro Goreleaser which can provide us with the templates functionality. Using templates we could have essentially two configs that could allow us to split CI up into two stages so we can use split permissions to accomplish our tasks using least privilege. 

There may also be other solutions or processes that could work for our use case too.
```[tasklist]
### Tasks
- [x] Decide on process to release to our homebrew-tap
- [x] Implement the process for releasing to our homebrew-tap
- [x] Test implementation to ensure proper functionality
- [x] Update documentation to explain the homebrew release process
```

**Comment by CloudBeard** [comment]
Completed as a part of https://github.com/defenseunicorns/lula/pull/319
